# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fast_article.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from GoogleTrans import GoogleTrans


def show_msg(msg):
    # 显示信息
    msg_box = QMessageBox(QMessageBox.Warning, '警告', msg)
    msg_box.show()
    msg_box.exec_()


class MainWin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.software_title = QtWidgets.QLabel(self.centralwidget)
        self.software_title.setGeometry(QtCore.QRect(360, 10, 111, 16))
        self.software_title.setObjectName("software_title")
        self.source_article = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.source_article.setGeometry(QtCore.QRect(40, 30, 711, 231))
        self.source_article.setObjectName("source_article")
        self.result_article = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result_article.setGeometry(QtCore.QRect(40, 300, 711, 211))
        self.result_article.setObjectName("result_article")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 280, 101, 16))
        self.label_2.setObjectName("label_2")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(610, 520, 141, 23))
        self.start_btn.setObjectName("start_btn")
        self.start_btn.clicked.connect(self.start)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "尘心伪原创工具V1.0"))
        self.software_title.setText(_translate("MainWindow", "尘心伪原创工具V1.0"))
        self.source_article.setPlainText(_translate("MainWindow", "这里输入原文章"))
        self.label_2.setText(_translate("MainWindow", "伪原创结果："))
        self.start_btn.setText(_translate("MainWindow", "开始伪原创"))

    def start(self):
        # 开始伪原创
        source_text = self.source_article.toPlainText().strip().replace('\n', '').replace('\r', '').replace(' ', '')
        if source_text is None or source_text == '':
            show_msg("您输入的文本为空!")
            return

        try:
            text = source_text
            original_text, original_language_code, target_text, target_language_code = GoogleTrans().query(text,
                                                                                                           lang_to='en')

            tt, ol, str, lt = GoogleTrans().query(target_text, lang_to='zh-CN')

            if str is not None and str != '':
                self.result_article.setPlainText(str)
            else:
                self.result_article.setPlainText("获取伪原创失败!")
        except Exception:
            show_msg("伪原创过程中出现异常!")